import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://balanceui.com";

  const routes = [
    "",
    "/components",
    "/docs",
    "/examples",
    "/license",
    "/privacy",
    "/terms",
    "/components/button",
    "/components/input",
    "/components/card",
    "/components/modal",
    "/components/dialog",
    "/components/datatable",
    "/components/formfield",
    "/components/select",
    "/components/textarea",
    "/components/badge",
    "/components/toast",
    "/components/drawer",
    "/components/sidebar",
    "/components/pagination",
    "/components/pagesizeselector",
    "/components/progress",
    "/components/shimmer",
    "/components/tree",
    "/components/accordion",
    "/components/tabs",
    "/components/stepper",
    "/components/toggle",
    "/components/tension",
    "/components/tensionrange",
    "/components/datepicker",
    "/components/timepicker",
    "/components/checkbox",
    "/components/bottomsheet",
    "/components/buttontoggle",
    "/components/icon",
    "/components/list",
    "/components/toolbar",
    "/components/videotrimmer",
    "/components/theme-preview",
    "/docs/getting-started",
    "/docs/installation",
    "/docs/theming",
    "/docs/api",
    "/docs/best-practices",
    "/docs/accessibility",
    "/examples/login-form",
    "/examples/dashboard",
    "/examples/settings",
    "/examples/wizard",
    "/examples/notifications",
    "/examples/catalog",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "daily" : "weekly",
    priority: route === "" ? 1 : 0.8,
  }));
}

